In [1]:
import numpy as np
import pandas as pd
from scipy.stats import f

In [10]:
# Data produksi tomat (kuintal/ha)
data_matrix = np.array([
    [5.1, 9.7, 5.9, 7.1, 6.2],
    [5.4, 9.1, 5.9, 9.5, 7.2],
    [5.2, 9.5, 9.5, 9.1, 7.6],
    [7.4, 9.9, 9.6, 6.5, 7.5],
    [9.9, 7.9, 7.3, 6.5, 8.4]
])

# Label perlakuan untuk setiap sel percobaan (harus sesuai desain Latin)
perlakuan_labels = np.array([
    ['A', 'B', 'C', 'D', 'E'],
    ['B', 'C', 'D', 'E', 'A'],
    ['C', 'D', 'E', 'A', 'B'],
    ['D', 'E', 'A', 'B', 'C'],
    ['E', 'A', 'B', 'C', 'D']
])

# Faktor koreksi
T = data_matrix.sum()
n = data_matrix.size

print("Data Produksi Tomat (kuintal/ha):")
print(data_matrix) 
print("\nLabel Perlakuan:")
print(perlakuan_labels)
print("\nFaktor Koreksi (T):", T)
print("Jumlah Data (n):", n)

Data Produksi Tomat (kuintal/ha):
[[5.1 9.7 5.9 7.1 6.2]
 [5.4 9.1 5.9 9.5 7.2]
 [5.2 9.5 9.5 9.1 7.6]
 [7.4 9.9 9.6 6.5 7.5]
 [9.9 7.9 7.3 6.5 8.4]]

Label Perlakuan:
[['A' 'B' 'C' 'D' 'E']
 ['B' 'C' 'D' 'E' 'A']
 ['C' 'D' 'E' 'A' 'B']
 ['D' 'E' 'A' 'B' 'C']
 ['E' 'A' 'B' 'C' 'D']]

Faktor Koreksi (T): 192.9
Jumlah Data (n): 25


In [11]:
# Langkah 1: Total dan Faktor Koreksi (FK)
T = data_matrix.sum()
FK = T**2 / n

In [12]:
print(f"Total (T): {T}")
print(f"Faktor Koreksi (FK): {FK}")

Total (T): 192.9
Faktor Koreksi (FK): 1488.4164


In [5]:
# Langkah 2: Jumlah Kuadrat Total (JKT)
JKT = np.sum(data_matrix**2) - FK

In [6]:
print(f"Total (JKT): {JKT}")

Total (JKT): 62.27359999999999


In [7]:
# Langkah 3: Jumlah Kuadrat Baris dan Kolom
total_baris = data_matrix.sum(axis=1)
total_kolom = data_matrix.sum(axis=0)
JK_baris = np.sum(total_baris**2) / 5 - FK
JK_kolom = np.sum(total_kolom**2) / 5 - FK

print(f"Jumlah Kuadrat Baris (JK_baris): {JK_baris}")
print(f"Jumlah Kuadrat Kolom (JK_kolom): {JK_kolom}")

Jumlah Kuadrat Baris (JK_baris): 7.1895999999997
Jumlah Kuadrat Kolom (JK_kolom): 18.13359999999966


In [13]:
# Hitung total per perlakuan
perlakuan_total = {p: data_matrix[perlakuan_labels == p].sum() for p in np.unique(perlakuan_labels)}

# Hitung JK Perlakuan
r = 5  # tiap perlakuan muncul 5 kali
JK_perlakuan = sum(Ti**2 for Ti in perlakuan_total.values()) / r - FK

print("JK Perlakuan =", round(JK_perlakuan, 4))

JK Perlakuan = 12.9816


In [14]:
# Langkah 5: JK Galat
JK_galat = JKT - JK_baris - JK_kolom - JK_perlakuan
print(f"JK Galat: {JK_galat}")

JK Galat: 23.968800000000783


In [15]:
# Derajat Bebas
db_baris = 4
db_kolom = 4
db_perlakuan = 4
db_galat = 12

In [16]:
# Kuadrat Tengah
KT_baris = JK_baris / db_baris
KT_kolom = JK_kolom / db_kolom
KT_perlakuan = JK_perlakuan / db_perlakuan
KT_galat = JK_galat / db_galat

print(f"Kuadrat Tengah Baris (KT_baris): {KT_baris}")
print(f"Kuadrat Tengah Kolom (KT_kolom): {KT_kolom}")
print(f"Kuadrat Tengah Perlakuan (KT_perlakuan): {KT_perlakuan}")
print(f"Kuadrat Tengah Galat (KT_galat): {KT_galat}")

Kuadrat Tengah Baris (KT_baris): 1.797399999999925
Kuadrat Tengah Kolom (KT_kolom): 4.533399999999915
Kuadrat Tengah Perlakuan (KT_perlakuan): 3.245399999999961
Kuadrat Tengah Galat (KT_galat): 1.9974000000000653


In [17]:
# F Hitung Perlakuan
F_perlakuan = KT_perlakuan / KT_galat
print(f"F Hitung Perlakuan: {F_perlakuan}")

F Hitung Perlakuan: 1.62481225593264


In [18]:
# F Tabel (5% dan 1% signifikansi)
F_tabel_5 = f.ppf(0.95, db_perlakuan, db_galat)
F_tabel_1 = f.ppf(0.99, db_perlakuan, db_galat)
print(f"F Tabel (5%): {F_tabel_5}")
print(f"F Tabel (1%): {F_tabel_1}")

F Tabel (5%): 3.259166726901249
F Tabel (1%): 5.4119514344731385


In [19]:
# Hasil analisis dalam bentuk dictionary
hasil = {
    "Total": T,
    "Faktor Koreksi (FK)": FK,
    "JKT": JKT,
    "JK Baris": JK_baris,
    "JK Kolom": JK_kolom,
    "JK Perlakuan": JK_perlakuan,
    "JK Galat": JK_galat,
    "KT Perlakuan": KT_perlakuan,
    "KT Galat": KT_galat,
    "F Hitung Perlakuan": F_perlakuan,
    "F Tabel 5%": F_tabel_5,
    "F Tabel 1%": F_tabel_1,
    "Keputusan": "Tolak H0 (ada pengaruh nyata)" if F_perlakuan > F_tabel_5 else "Gagal Tolak H0 (tidak ada pengaruh signifikan)"
}

hasil_df = pd.DataFrame.from_dict(hasil, orient='index', columns=["Nilai"])
hasil_df

Nilai
Total                                                         192.9
Faktor Koreksi (FK)                                       1488.4164
JKT                                                         62.2736
JK Baris                                                     7.1896
JK Kolom                                                    18.1336
JK Perlakuan                                                12.9816
JK Galat                                                    23.9688
KT Perlakuan                                                 3.2454
KT Galat                                                     1.9974
F Hitung Perlakuan                                         1.624812
F Tabel 5%                                                 3.259167
F Tabel 1%                                                 5.411951
Keputusan            Gagal Tolak H0 (tidak ada pengaruh signifikan)

In [20]:
# Menyusun tabel ANOVA sebagai DataFrame
anova_table = pd.DataFrame({
    "Sumber": ["Baris", "Kolom", "Perlakuan", "Galat", "Total"],
    "JK": [JK_baris, JK_kolom, JK_perlakuan, JK_galat, JKT],
    "db": [db_baris, db_kolom, db_perlakuan, db_galat, 24],
    "KT": [KT_baris, KT_kolom, KT_perlakuan, KT_galat, ""],
    "F Hitung": ["", "", F_perlakuan, "", ""]
})

anova_table

Sumber       JK  db      KT  F Hitung
0      Baris   7.1896   4  1.7974          
1      Kolom  18.1336   4  4.5334          
2  Perlakuan  12.9816   4  3.2454  1.624812
3      Galat  23.9688  12  1.9974          
4      Total  62.2736  24